name: Run mkepg.sh with jq

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # Каждый день в 02:00 UTC

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        # Используйте последнюю версию для лучшей совместимости
        uses: actions/checkout@v4 
    
      - name: Run mkepg.sh
        run: |
          # Включение вывода ошибок shell (-e) уже должно быть в bash,
          # но явное указание помогает.
          bash mkepg.sh > epgm.xml
    
      - name: Archive epgm.xml
        run: gzip -f epgm.xml
          
      - name: Commit and push changes
        run: |
          # 1. Настройка пользователя
          git config user.name github-actions
          git config user.email your-email@example.com
          
          # 2. Проверка, есть ли что-то для коммита
          if [ -z "$(git status --porcelain)" ]; then
            echo "Нет изменений для коммита. Выход."
          else
            # 3. Добавление и коммит изменений
            git add epgm.xml.gz
            git commit -m "Convert JSON to XMLTV and archive"
            
            # 4. ОБЯЗАТЕЛЬНЫЙ ШАГ: Получить последние изменения перед отправкой
            # Это решает проблему "rejected push"
            git pull origin main --rebase 
            
            # 5. Отправка изменений
            git push
          fi
